- hosts: localhost
  vars:
     needs_desktop: "{{ 'desktop' in ansible_run_tags | default([]) }}"
     needs_laptop: "{{ 'laptop' in ansible_run_tags | default([]) }}"
     dotfiles_core: "{{ 'dotfiles_core' in ansible_run_tags | default([]) }}"
     current_user: "{{ lookup('pipe', 'whoami') }}"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags: always
  tasks:
    - include_tasks: tasks/core-stuff.yml
      tags:
        - core
    - include_tasks: tasks/zsh-setup.yml
      tags:
        - core
    - include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
    - include_tasks: tasks/productivity-tools.yml
      tags:
        - core
    - include_tasks: tasks/desktop-apps.yml
      when: needs_desktop
      tags:
        - desktop
    - include_tasks: tasks/neovim.yml
      tags:
        - neovim
    - include_tasks: tasks/languages.yml
      tags:
        - languages
