- hosts: localhost
  vars:
     needs_desktop: "{{ 'desktop' in ansible_run_tags | default([]) }}"
     needs_laptop: "{{ 'laptop' in ansible_run_tags | default([]) }}"
     current_user: "{{ lookup('pipe', 'whoami') }}"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include_tasks: tasks/core-stuff.yml
      tags:
        - install
        - shell
        - core
    - include_tasks: tasks/zsh-setup.yml
      tags:
        - install
        - zsh
        - shell
    - include_tasks: tasks/productivity-tools.yml
      tags:
        - install
        - shell
        - productivity
    - include_tasks: tasks/desktop-apps.yml
      when: needs_desktop
      tags:
        - install
        - core
        - desktop
    - include_tasks: tasks/eza-install.yml
      tags:
        - install
        - shell
        - productivity
    - include_tasks: tasks/dotfiles.yml
      tags:
        - setup
        - dotfiles
        - shell
        - gitconfig_school
