- hosts: localhost
  pre_tasks:
    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: current_user_whoami
    - set_fact:
        current_user: "{{ current_user_whoami.stdout }}"
    - debug: var=current_user
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include_tasks: tasks/core-stuff.yml
      tags:
        - install
        - shell
        - core
    - include_tasks: tasks/zsh-setup.yml
      tags:
        - install
        - zsh
        - shell
    - include_tasks: tasks/productivity-tools.yml
      tags:
        - install
        - shell
        - productivity
    - include_tasks: tasks/eza-install.yml
      tags:
        - install
        - shell
        - productivity
    - include_tasks: tasks/dotfiles.yml
      tags:
        - setup
        - dotfiles
        - shell
