- name: Install core stuff from apt (1st)
  become: true
  apt:
    name: [ 'xterm' ]
  tags:
    - install
    - shell
    - core
- name: Install desktop only core stuff from apt
  become: true
  apt:
    name: [ 'feh' ]
  when: needs_desktop
  tags:
    - desktop
    - install
    - core
