- name: Install core stuff from apt (1st)
  become: true
  apt:
    name: [ 'flatpak', 'playerctl', 'maim', 'imagemagick' ]
  tags:
    - install
    - shell
    - core
- name: Add flathub to flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags:
    - install
    - core
- name: Install desktop only core stuff from apt
  become: true
  apt:
    name: [ 'feh', 'xterm', 'i3' ]
  when: needs_desktop
  tags:
    - desktop
    - install
    - core
