- name: Install core stuff from apt (1st)
  become: true
  apt:
    name: [ 'flatpak', 'playerctl', 'tmux', 'xclip', 'fd-find', 'inotify-tools' ]
  tags:
    - install
    - shell
    - core
- name: Add flathub to flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags:
    - install
    - core
- name: Install desktop only core stuff from apt
  become: true
  apt:
    name: [ 'feh', 'xterm', 'i3', 'maim', 'imagemagick', 'xdotool', 'rofi', 'qbittorrent', 'compton' ]
  when: needs_desktop
  tags:
    - desktop
    - install
    - core
- name: Check if lucide font is already installed
  shell: fc-list | grep "lucide"
  register: font_check_result
  changed_when: false
  ignore_errors: true
  when: needs_desktop
  tags:
   - desktop
   - install
   - core
- name: Set fact if lucide installed
  set_fact:
    font_installed: "{{ font_check_result.rc == 0 }}"
  when: needs_desktop
  tags:
    - desktop
    - install
    - core
- name: Download lucide from GitHub
  get_url:
    url: https://github.com/lucide-icons/lucide/releases/download/0.378.0/lucide-font-0.378.0.zip
    dest: /tmp/lucide-font-0.378.0.zip
  when: needs_desktop and not font_installed
  tags:
    - desktop
    - install
    - core
- name: Unzip lucide zip
  unarchive:
    src: /tmp/lucide-font-0.378.0.zip
    dest: /tmp/
  when: needs_desktop and not font_installed
  tags:
    - desktop
    - install
    - core
- name: Move lucide.ttf to /usr/local/share/fonts
  become: true
  copy:
    src: /tmp/lucide-font/lucide.ttf
    dest: /usr/local/share/fonts/
    owner: root
    group: root
    mode: '0644'
  when: needs_desktop and not font_installed
  tags:
    - desktop
    - install
    - core
- name: Reload fonts cache
  become: true
  command: fc-cache -f -v
  when: needs_desktop and not font_installed
  tags:
    - desktop
    - install
    - core
- name: Download greenclip
  become: true
  when: needs_desktop
  get_url:
    url: https://github.com/erebe/greenclip/releases/download/v4.2/greenclip
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/greenclip"
    mode: "0755"
  tags:
    - desktop
    - install
    - core
- name: Download brightnessclt
  become: true
  when: needs_laptop
  apt:
    name: brightnessctl
  tags:
    - laptop
    - install
    - core
- name: Modify brightessctl permission
  become: true
  when: needs_laptop
  shell: chmod +s $(which brightnessctl)
  tags:
    - laptop
    - install
    - core
- name: Install fmn (node and npm version manager)
  shell: curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
  tags:
    - install
    - core
