- name: Install stow
  become: true
  apt: name=stow
  tags: &tags_for_dotfiles [ 'setup', 'dotfiles', 'shell' ]

- name: Clone .dotfiles repo
  ansible.builtin.git:
    repo: "https://github.com/11Firefox11/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: no
    accept_hostkey: yes
    version: main
  when: "'stow' not in ansible_run_tags"
  tags: *tags_for_dotfiles

- name: Set git skip-worktree for school gitconfig
  command: git update-index --skip-worktree "{{ lookup('env', 'HOME') }}/.dotfiles/git/.gitconfig-school"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles/"
  tags:
    - gitconfig_school

- name: Decrypt school gitconfig via ansible vault
  command:
    cmd: ansible-vault decrypt "{{ lookup('env', 'HOME') }}/.dotfiles/git/.gitconfig-school"
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles/" 
  tags:
    - gitconfig_school

- name: Stow dotfiles
  command:
    cmd: bash ./install
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles/"
  tags: *tags_for_dotfiles

- name: Check if xrdb command exists
  shell: command -v xrdb > /dev/null 2>&1
  register: xrdb_check
  ignore_errors: true
  when: needs_desktop
  tags:
    - desktop

- name: Reload xterm
  command: xrdb -merge ~/.Xresources
  when: "needs_desktop and xrdb_check.rc == 0"
  tags:
    - desktop

- name: Enable ssh agent service
  command: systemctl --user enable ssh-agent.service
  when: needs_desktop
  tags:
    - desktop

- name: Check if i3-msg command exists
  shell: command -v i3-msg > /dev/null 2>&1
  register: i3msg_check
  ignore_errors: true
  when: needs_desktop
  tags:
    - desktop

- name: Reload i3
  command: i3-msg reload
  when: "needs_desktop and i3msg_check.rc == 0"
  tags:
    - desktop

- name: Check if tmux command exists
  shell: command -v tmux > /dev/null 2>&1
  register: tmux_check
  ignore_errors: true
  tags: *tags_for_dotfiles

- name: Reload tmux
  command: tmux source-file ~/.tmux.conf
  when: "tmux_check.rc == 0"
  tags: *tags_for_dotfiles

- name: Install urgent watcher pip dependency
  command: pip install i3ipc
  when: needs_desktop
  tags:
    - desktop
