- name: Install stow
  become: true
  apt: name=stow
  tags: &tags_for_dotfiles [ 'setup', 'dotfiles', 'shell' ]

- name: Clone .dotfiles repo
  ansible.builtin.git:
    repo: "https://github.com/11Firefox11/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: no
    accept_hostkey: yes
    version: main
  when: "'stow' not in ansible_run_tags"
  tags: *tags_for_dotfiles

- name: Set git skip-worktree for school gitconfig
  command: git update-index --skip-worktree "{{ lookup('env', 'HOME') }}/.dotfiles/git/.gitconfig-school"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles/"
  tags:
    - gitconfig_school

- name: Decrypt school gitconfig via ansible vault
  command:
    cmd: ansible-vault decrypt "{{ lookup('env', 'HOME') }}/.dotfiles/git/.gitconfig-school"
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles/" 
  tags:
    - gitconfig_school

- name: Set git skip-worktree for gp-config nvim
  command: git update-index --skip-worktree "{{ lookup('env', 'HOME') }}/.dotfiles/nvim/.config/nvim/gp-config.lua"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles/"
  tags:
    - gp_config

- name: Decrypt gp-config nvim via ansible vault
  command:
    cmd: ansible-vault decrypt "{{ lookup('env', 'HOME') }}/.dotfiles/nvim/.config/nvim/gp-config.lua"
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles/" 
  tags:
    - gp_config

- name: Stow dotfiles
  command:
    cmd: bash ./install
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles/"
  tags: *tags_for_dotfiles

- name: Enable ssh agent service
  command: systemctl --user enable ssh-agent.service
  when: needs_desktop
  tags:
    - desktop

- name: Install urgent watcher pip dependency
  command: pip install i3ipc
  when: needs_desktop
  tags:
    - desktop
