- name: Install stow
  apt: name=stow

- name: Clone .dotfiles repo
  ansible.builtin.git:
    repo: 'git@github.com:11Firefox11/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
