- name: Install tools from apt (1st)
  become: true
  apt:
    name: [ 'xclip', 'fzf' ]
  tags:
    - install
    - shell

- name: Ensure ~/.local/bin directory exists
  file:
    path: "~/.local/bin"
    state: directory
  tags:
    - install
    - shell
    - productivity

- name: Install tldr
  get_url:
    url: https://raw.githubusercontent.com/pepa65/tldr-bash-client/master/tldr
    dest: "~/.local/bin/"
    mode: '+x'
  tags:
    - install
    - shell
    - productivity

- name: Modify less in tldr
  command: sed -i 's/less -Gg -~RXQFP/less -QP/g' ~/.local/bin/tldr
  tags:
    - install
    - shell
    - productivity

- name: Install bat
  become: true
  apt:
    name: bat
    state: present
    update_cache: yes
  tags:
    - install
    - shell
    - productivity

- name: Create symbolic link for batcat
  file:
    src: "/usr/bin/batcat"
    dest: "~/.local/bin/bat"
    state: link
  tags:
    - install
    - shell
    - productivity

- name: Install zoxide
  shell: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
  args:
    executable: /bin/sh
  become_user: "{{ current_user }}"
  tags:
    - install
    - shell
    - productivity
