- name: Install xclip
  become: true
  apt:
    name: [ 'xclip' ]
  tags:
    - install
    - shell

- name: Install tldr
  become: true
  get_url:
    url: https://raw.githubusercontent.com/raylee/tldr/master/tldr
    dest: /bin/
    mode: '+x'
  tags:
    - install
    - shell
    - productivity
