- name: Install tools from apt (1st)
  become: true
  apt:
    name: [ 'xclip', 'fzf' ]
  tags:
    - install
    - shell

- name: Install tldr
  become: true
  get_url:
    url: https://raw.githubusercontent.com/raylee/tldr/master/tldr
    dest: /bin/
    mode: '+x'
  tags:
    - install
    - shell
    - productivity

- name: "{{ current_user }}"
  shell: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
  args:
    executable: /bin/sh
  become_user: "{{ current_user }}"
  tags:
    - install
    - shell
    - productivity
