- name: Install ZSH
  become: true
  apt:
    name: zsh
    state: present

- name: Set ZSH as default shell
  user:
    name: "{{ current_user }}"
    shell: "{{ lookup('pipe', 'which zsh') }}"
  become: true

- name: Check if Oh My Zsh is already installed
  stat:
    path: "/home/{{ current_user }}/.oh-my-zsh"
  register: oh_my_stats

- name: Install Oh My Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: not oh_my_stats.stat.exists
  become_user: "{{ current_user }}"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
